### ISSUE TITLE
The Slide of Chat window of the blockchain expert is incorrect

### ISSUE THREAD

**Issue by zhengqian8958** [WTFTown/feedback#1]
## Description
The chat window of blockchain expert is moved up unexpectly if the conversition text is exceed the chat window hight

## To Reproduce
1. Go to Blockchain Expert
2. Type "X" to start conversation
3. Type "Y" to start chat window
4. Keep chat with bot until the text size is over the chat window hight
5. See the issue

## Expected Behavior
Chat window's possition keep no change, but only the conversition text slide up

## Screenshots
![image](https://github.com/WTFTown/feedback/assets/96370574/625625ad-629d-439c-bd66-1248290377c8)

## Environment
- OS: windows 10
- Browser: Chrome
- Version: 124.0.6367.119

## Additional Context
None

## Logs
None

**Comment by AmazingAng** [comment]
这个bug我也遇到过，不过之前没重现出来。
感谢报告

**Comment by buttonwild** [comment]
一样的问题
![image](https://github.com/WTFTown/feedback/assets/33722083/7873b720-eacd-4286-8264-b2b9c5e2aad9)

环境：
OS: windows 11
Browser: Microsoft Edge
Version: 124.0.2478.80 (正式版本) (64 位)

**Comment by buttonwild** [comment]
我觉得可以使用同样的会话测试是否有问题

**Comment by AmazingAng** [comment]
好的

**Comment by dxiongya** [comment]
修正中

**Comment by ariesjia** [comment]
fixed
